name: smartlogproject
description: A new Flutter project

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <4.0.0"

dependencies:
  intl: ^0.16.1
  cloud_firestore: ^0.13.7
  firebase_auth: ^0.16.1
  firebase_core: ^0.4.3
  firebase_auth_web: ^0.1.3+1
  flutter:
    sdk: flutter
  slidy: ^2.1.2+2
  masked_text: ^0.0.6
  bloc_pattern: ^1.1.0
  dio: ^3.0.9
  rxdart: ^0.19.0
  mobx:  ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  observable: ^0.22.2
  firebase_database: ^3.1.6
  google_maps_flutter: ^0.5.29
  google_maps: ^3.4.4
  date_format: ^1.0.9
  flutter_email_sender: ^3.0.1
  mailer: ^3.0.4
  url_launcher: ^5.7.2


  font_awesome_flutter: ^8.5.0

  flutter_masked_text: ^0.8.0

  google_fonts: ^0.3.9

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  assets:
    - Images/user_logo.png
    - Images/veiculo.png
    - Images/embalagem.png
    - Images/money.png
    - Images/enterprise.png
    - Images/contrato_venda.png
    - Images/carga.png
    - Images/romaneio.png
    - Images/login.png
    - Images/combustivel.png
    - Images/manutencao.png
    - Images/oleo.png
    - Images/fundosistema.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Lobster
      fonts:
        - asset: fontes/Lobster-Regular.ttf
          weight: 700
    - family: Satisfy
      fonts:
        - asset: fontes/Satisfy-Regular.ttf

    - family: Cardo
      fonts:
        - asset: fontes/Cardo-Regular.ttf
          
    # - family: Trajan Pro
    #   fonts:
    #     - asset: fonts/TrajanPro.ttf
    #     - asset: fonts/TrajanPro_Bold.ttf
    #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
